### ISSUE TITLE
把ui放到阿里云环境部署后，无法打开界面  3.1 版本。

### ISSUE THREAD

**Issue by liuchang0403** [wu-sheng/sky-walking-ui#27]
require.min.js:5 Uncaught Error: Load timeout for modules: vis,echarts
http://requirejs.org/docs/errors.html#timeout
    at makeError (require.min.js:5)
    at l (require.min.js:5)
    at require.min.js:5

这是报错信息

**Comment by pengys5** [comment]
@liuchang0403 此bug已修复，此问题的原因是你的电脑到阿里云主机的网络环境不好，下载vis.js超时，目前已将超时时间延长。
