### ISSUE TITLE
时间显示不正确

### ISSUE THREAD

**Issue by mmaxiaolei** [wu-sheng/sky-walking-ui#33]
界面显示时间比实际早了将近8小时。应该是用docker启动的后端服务的原因，docker没有主动设置过时区。

**Comment by wu-sheng** [comment]
@mmaxiaolei Skywalking PMC专门组会讨论了你反映的问题，根据商用和开源APM的通行做法，不会通过APM系统来校准时间，具体原因如下：

1. 通过Collector校准时间，如果各探针时区不一致，则会造成负面影响
1. 如果通过探针来校准时间，则需要逐一修改探针配置，和逐一调整操作系统或者容器时间设置无区别，且每次部署新引用都需要手动调整，工作量大，效果不好。
1. 根据通行做法，APM如实按照客户端时间进行处理，避免和日志中的时间不一致，对信息整合分析造成不可预知的影响
1. 目前主流的追踪或APM系统，都不进行此类操作。

综上，此问题将不通过代码方式进行修复。建议在DockerFile中增加修改时区的脚本，避免此问题。感谢你的问题反馈。

By PMC, @wu-sheng
