### ISSUE TITLE
trace界面显示建议

### ISSUE THREAD

**Issue by mmaxiaolei** [wu-sheng/sky-walking-ui#34]
trace界面列表建议只显示trace的第1级，并且按照时间倒序排序。目前的列表展示的内容比较混乱。

**Comment by wu-sheng** [comment]
@mmaxiaolei 抱歉，等待这么长时间才回复此问题。我们在所有issue都在skywalking主工程管理，之后请在那里提交问题，谢谢。

9月中旬发布的3.2版本，已经增加trace的查询功能。支持按照时间倒序排列，请参考截图：https://camo.githubusercontent.com/5e9ca1f32c8d6d9b8da8be3c66ef65984bbd140d/68747470733a2f2f736b792d77616c6b696e672e6769746875622e696f2f706167652d7265736f75726365732f332e322f74726163655f7365676d656e742e706e67

显示一级trace因为涉及对批量的后续支持，暂时保持不变。
