### ISSUE TITLE
In Win7, if the project path has spaces, start failure, no prompt

### ISSUE THREAD

**Issue by WallC0902** [wu-sheng/sky-walking-ui#8]
在wind7中，如果项目路径中有空格，启动失败，没有提示。

**Comment by ascrutae** [comment]
I cannot reproduce this bug. Here is the picture that skywalking-ui running at win7 environment.
<img width="841" alt="wx20170425-233230 2x" src="https://cloud.githubusercontent.com/assets/12436447/25414317/7cae2bec-2a63-11e7-8c34-669a17e7a506.png">

**Comment by wu-sheng** [comment]
@WallC0902 Please recheck this. If this issue still exists, please reopen this issue.
